# Generated by Django 4.0.6 on 2022-07-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_instrumento', models.CharField(max_length=30)),
                ('tipo_instrumento', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(null=True)),
            ],
        ),
    ]
