# Generated by Django 4.0.6 on 2022-07-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumento',
            old_name='nombre_instrumento',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='instrumento',
            old_name='tipo_instrumento',
            new_name='tipo',
        ),
    ]
